import Head from 'next/head'
import Meetups from '../components/Meetups/Meetups';
import { getMeetups } from '../lib/meetups';

export default function Home({ meetups }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='mt-28'>
          <div className='container'>
            {/* Meetups Render */}
            <Meetups meetups={meetups}/>
          </div>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  // fetch data
  const meetups_data = await getMeetups();

  // return data
  return {
    props: {
      meetups: meetups_data
    }
  }
}
